config/routes.rb
Rails.application.routes.draw do

  root "top#index"
  get "about" => "top#about", as: "about"
  get "contact" => "top#contact"
  get "/signup", to: "members#new"
  post "/signup", to: "members#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :members do
    resources :entries, only: [:index]
    get :following, :followers, on: :member
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :articles, only: [:index, :show]
  resources :relationships,       only: [:create, :destroy]
  resources :entries do
    patch :like, :unlike, on: :member
    get :voted, on: :collection
    resources :images, controller: "entry_images" do
      patch :move_higher, :move_lower, on: :member
    end
  end

  namespace :admin do
    root to: "top#index"
    resources :members do
      get "search", on: :collection
    end
    resources :articles
  end
end

app/models/entry_image.rb
class EntryImage < ApplicationRecord
  belongs_to :entry
  has_one_attached :data
  acts_as_list scope: :entry

  attribute :new_data

  validates :new_data, presence: { on: :create }

  validate if: :new_data do
    if new_data.respond_to?(:content_type)
      unless new_data.content_type.in?(ALLOWED_CONTENT_TYPES)
        errors.add(:new_data, :invalid_image_type)
      end
    else
      errors.add(:new_data, :invalid_image_type)
    end
  end

  before_save do
    self.data = new_data if new_data
  end
end

app/controllers/entry_images_controller.rb
class EntryImagesController < ApplicationController
  before_action :login_url

  before_action do
    @entry = current_member.entries.find(params[:entry_id])
  end

  def index
    @images = @entry.images.order(:position)
  end

  def show
    redirect_to action: "edit"
  end

  def new
    @image = @entry.images.build
  end

  def edit
    @image = @entry.images.find(params[:id])
  end

  def create
    @image = @entry.images.build(image_params)
    if @image.save
      redirect_to [@entry, :images], notice: "画像を作成しました。"
    else
      render "new"
    end
  end

  def update
    @image = @entry.images.find(params[:id])
    @image.assign_attributes(image_params)
    if @image.save
      redirect_to [@entry, :images], notice: "画像を更新しました。"
    else
      render "eidt"
    end
  end

  def destroy
    @image = @entry.images.find(params[:id])
    @image.destroy
    redirect_to [@entry, :images], notice: "画像を削除しました。"
  end

  def move_higher
    @image = @entry.images.find(params[:id])
    @image.move_higher
    redirect_back fallback_location: [@entry, :images]
  end

  def move_lower
    @image = @entry.images.find(params[:id])
    @image.move_lower
    redirect_back fallback_location: [@entry, :images]
  end
  
  private

  def image_params
    params.require(:image).permit(:new_data, :alt_text)
  end
end

app/views/entry_images/_form.html.erb
<!-- エラーコード書く -->

<table class="attr" border="2">
  <tr>
    <th class="pic-info" width="100"><%= form.label :new_data %></th>
    <td><%= form.file_field :new_data, :class => "btn btn-data" %></td>
  </tr>
  <tr>
    <th class="article-name"><%= form.label :alt_text %></th>
    <td><%= form.text_field :alt_text, size: 40, :class => "image-field" %></td>
  </tr>
</table>

app/views/entry_images/edit.html.erb
<% provide(:title, 'ブログ記事の画像編集') %>
<div class="entry-images-new">ブログ記事の画像編集</div>
<h2><%= @entry.title %></h2>

<% url = entry_image_path(@entry, @image) %>
<%= form_for @image, as: "image", url: url do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit '更新', class: 'btn btn-primary' %></div>
<% end %>

app/views/entry_images/index.html.erb
<% provide(:title, 'ブログ記事の画像') %>
<h1>ブログ記事の画像</h1>
<h2><%= @entry.title %></h2>

<ul class="toolbar">
  <%= menu_link_to "ブログ記事に戻る", @entry %>
  <%= menu_link_to "画像の追加", [:new, @entry, :image] %>
</ul>

<% if @images.present? %>
  <table class="list" border="2">
    <thead>
      <tr>
        <th>番号</th>
        <th>画像</th>
        <th>代替テキスト</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @images.each_with_index do |image, index| %>
        <tr>
          <td class="image-number"><%= index + 1 %></td>
          <td class="image-entries-setup">
            <%= image_tag image.data.variant(resize: "100x>"),
              alt: image.alt_text %>
          </td>
          <td class="image-text">
            <%= image.alt_text %>
          </td>
          <td>
            <div class="entries-post-image">
              <%= link_to "編集", edit_entry_image_path(@entry, image) %> |
              <%= link_to "削除", entry_image_path(@entry, image),
                method: :delete, data: { confirm: "本当に削除しますか？" } %>
            </div>
            <div class="image-down_up">
              <%= link_to_unless image.first?, "上へ",
                move_higher_entry_image_path(@entry, image),
                method: :patch %> |
                <%= link_to_unless image.last?, "下へ",
                  move_lower_entry_image_path(@entry, image),
                  method: :patch %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>画像がありません。</p>
<% end %>

app/views/entry_images/new.html.erb
<% provide(:title, 'ブログ記事への画像追加') %>
<div class="entry-images-new">ブログ記事への画像追加</div>
<h2><%= @entry.title %></h2>

<% url = entry_images_path(@entry, @image) %>
<%= form_for @image, as: "image", url: url do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit '登録', class: 'btn btn-primary' %></div>
<% end %>