config/routes.rb
Rails.application.routes.draw do

  root "top#index"
  get "about" => "top#about", as: "about"
  get "contact" => "top#contact"
  get "/signup", to: "members#new"
  post "/signup", to: "members#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :members do
    resources :entries, only: [:index]
    get :following, :followers, on: :member
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :articles, only: [:index, :show]
  resources :relationships,       only: [:create, :destroy]
  resources :entries do
    patch :like, :unlike, on: :member
    get :voted, on: :collection
    resources :images, controller: "entry_images" do
      patch :move_higher, :move_lower, on: :member
    end
  end

  namespace :admin do
    root to: "top#index"
    resources :members do
      get "search", on: :collection
    end
    resources :articles
  end
end

app/views/shared/_admin_menubar.html.erb
<nav class="menubar" id="admin-menubar">
  <ul>
    <%= menu_link_to "管理TOP", :admin_root %>
    <%= menu_link_to "会員管理", :admin_members %>
    <%= menu_link_to "ニュース記事管理", :admin_articles %>
    <%= menu_link_to "TOP", :root %>
  </ul>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", :about %> |
Copyright (C) <%= link_to "Contact", :contact %>
Since-2018

app/views/shared/_header.html.erb
<%= image_tag "coollogo_com-21817846.png", size: "272x48", alt: "NM Helth Food Web Shop", :class => "logos" %>

<%=
  if controller.kind_of?(Admin::Base)
    render "shared/admin_menubar"
  else
    render "shared/menubar"
  end
%>

app/views/shared/_login_form.html.erb
<% unless logged_in? %>
  <h2 class="btn-button"><%= link_to "Sign up!", :signup, class: "btn btn-info" %></h2>
<% end %>

<% unless logged_in? %>
  <h2 class="btn-login"><%= link_to "Login", login_path, class: "btn btn-default" %></h2>
<% end %>

app/views/shared/_menubar.html.erb
<nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", :root %>
    <%= menu_link_to "About", :about %>
    <%= menu_link_to "ニュース", :articles %>
    <%= menu_link_to "ブログ", :entries %>
    <% if logged_in? %>
      <li><%= menu_link_to "会員名簿", :members, class: "header-menu" %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_member %></li>
          <li><%= link_to "Settings", edit_member_path(current_member) %></li>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %>
        </li>
    </ul>
  </li>
      <% if current_member.admin? %>
        <%= menu_link_to "管理ページ", :admin_root %>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" %>

<h2>最新ニュース</h2>
<%
  articles = Article.visible.order(released_at: :desc).limit(5)
  articles = articles.open_to_the_public unless current_member
%>
<ul>
  <% articles.each do |article| %>
    <li><%= link_to article.title, article %></li>
  <% end %>
</ul>

<h2>会員のブログ</h2>
<%
  entries = Entry.readable_for(current_member)
    .order(posted_at: :desc).limit(5)
%>
<ul>
  <% entries.each do |entry| %>
    <li>
      <%= link_to entry.title, entry %>
      by <%= link_to entry.author.name, [entry.author, :entries] %>
    </li>
  <% end %>
</ul>

app/views/shared/_stats.html.erb
<% @member ||= current_member %>
<div>
  <a class="user-following" href="<%= following_member_path(@member) %>">
    <strong id="following" class="stat">
      <%= @member.following.count %>
    </strong>
    following
  </a><br>
  <a class="user-followers" href="<%= followers_member_path(@member) %>">
    <strong id="followers" class="stat">
      <%= @member.followers.count %>
    </strong>
    followers
  </a>
</div>